Helcaraxan/gomod

README.md
=> Add CI badges on README.md

README.md
Pull request for this issue: https://github.com/Helcaraxan/gomod/issues/13
=> Add link to graphviz to readme

RELEASE_NOTES.md
Prepare the v0.4.0 release by cutting the current release notes and preparing the new section for the next release.
N.A.
=> Cut release-notes for v0.4.0

RELEASE_NOTES.md, lib/analysis/analysis.go, lib/depgraph/filter.go, lib/depgraph/graph.go, lib/depgraph/map.go, lib/depgraph/map_test.go, lib/depgraph/parser.go, lib/printer/clustering.go, lib/printer/printer.go, lib/reveal/replacements.go
Reworking type names for consistency and readability purposes.
N.A.
=> Types and fields consolidation

RELEASE_NOTES.md, lib/depgraph/filter.go, main.go
Reworking function and type names for consistency and readability purposes as well as some logic refactoring.
N.A.
=> Refactor and clean-up depgraph filtering logic

RELEASE_NOTES.md, lib/depgraph/filter.go, lib/depgraph/graph.go, lib/depgraph/map.go, lib/depgraph/map_test.go, lib/depgraph/parser.go, lib/reveal/replacements_test.go
Reworking type names for consistency and readability purposes, as well as some clean-up.
N.A.
=> Renaming of NodeMap types and methods

RELEASE_NOTES.md, lib/depgraph/graph.go, lib/depgraph/map_test.go, lib/depgraph/parser.go, lib/modules/modules.go, lib/reveal/replacements.go, lib/reveal/replacements_test.go
Moving the `Module` related types to a separate package to expand functionality in the future.
Test coverage remains the same.
=> Migrate Module type to own package

RELEASE_NOTES.md, lib/depgraph/parser.go, lib/modules/modules.go, lib/modules/modules_test.go, lib/modules/testdata/NoModule.yaml
Extension of the APIs enabling the querying of module information in preparation for subsequent improvements to the `gomod analyse` command.
The existing tests have been expanded to maintain overall code coverage on all new functionalities.
=> Extend module information retrieval API

README.md, RELEASE_NOTES.md, lib/analysis/analysis.go, lib/analysis/analysis_test.go, lib/analysis/testdata/DeprecatedUpdate.yaml, lib/analysis/testdata/MissingTimestamp.yaml, lib/analysis/testdata/NoUpdates.yaml, lib/analysis/testdata/OneDep.yaml, lib/analysis/testdata/OneDirectOneIndirect.yaml, lib/analysis/testdata/TwoDeps.yaml, lib/depgraph/graph.go, lib/depgraph/parser.go, lib/internal/testutil/test_module.go, lib/modules/modules.go, lib/modules/modules_test.go, lib/modules/testdata/GoListError.yaml, lib/modules/testdata/InvalidListOutput.yaml, lib/modules/testdata/LoadError.yaml, lib/modules/testdata/LoadErrorNotFatal.yaml, lib/modules/testdata/NoDependencies.yaml, lib/modules/testdata/NoModule.yaml, lib/modules/testdata/ReplacedDependency.yaml, lib/modules/testdata/go, lib/reveal/replacements_test.go, main.go
The existing dependency age analysis only gives a partial picture as some dependencies might be old but only because there are no more recent commits / versions available. This PR adds an additional analysis elements which evaluates the "update backlog", meaning the time difference between the version in use and the most recent update, if any are available.
This PR also adds full testing for the `lib/analysis` package which only had very partial coverage up to this point. Most importantly the added tests use the testing harness implemented for `lib/modules` and as such are more end-to-end focused rather than being pure unit-tests.
=> Update backlog analysis support

README.md, lib/analysis/analysis.go, lib/analysis/testdata/MissingTimestamp.yaml, lib/analysis/testdata/OneDep.yaml, lib/analysis/testdata/OneDirectOneIndirect.yaml, lib/analysis/testdata/TwoDeps.yaml
Knowing how many updates are available for your dependencies is good. Better is to also know how much of those updates concern direct dependencies, which are the only ones you can influence reliably without resorting to `replace` statements.
Updated tests for the affected code paths.
=> Improve backlog report quality

RELEASE_NOTES.md
Notes for the 0.5.0 release.
N.A.
=> Cut release-notes for v0.5.0

ci/release.sh
Doing releases manually is cumbersome and error-prone. Automation is better. This PR introduces a first script that automates the build, tag, push logic as well as the GitHub API calls to create a release an upload the corresponding assets.
Equipping the script to be unit-testable would make the script somewhat less readable but might be a future aim (or just move it to a Go "script"). It has however been manually tested and validated and is ready for use.
=> Add a release script

README.md, ci/release.sh
Because nit-picks do matter!
N.A.
=> Fix mini nitpicks

ci/test.sh
Accurately find code coverage for _all_ packages, given that some tests cover beyond the package they are part of.
N.A.
=> Amend test code coverage setup

.github/workflows/premerge.yaml, ci/lint.sh, go.mod
Enable CI via GitHub Actions
N.A
=> Enable GitHub Actions

lib/depgraph/filters/target_dependency.go
Removing some erroneous handling of filter based on a misuse of a `map` type.
N.A
=> Further fix dependency filtering

RELEASE_NOTES.md, ci/release.sh, main.go, main_strings.go
Also fix a nil-reference panic error when running unknown commands to
gomod.
Closes #51.
N.A
=> Add a version command

.github/workflows/premerge.yaml
Upgrade the version Go used in CI to latest.
No new tests.
=> Bump Go version in CI to 1.15

internal/analysis/analysis.go, internal/depgraph/filters/non_shared_modules.go, internal/depgraph/graph.go, internal/depgraph/module.go, internal/depgraph/parser.go, internal/graph/graph.go, internal/graph/graph_test.go, internal/graph/node.go, internal/graph/node_test.go, internal/reveal/replacements.go, main.go
Adding some much-needed unit-tests to cover the entirety of the recently split-out `graph` package.
Tests, tests, tests... there are tests everywhere in this PR.
=> Simplify Graph struct and add unit-tests

main.go
Log output needs to be directed to `stderr` to enable a clean separation between it and the actual `dot` output produced by `gomod`.
Closes #76.
N.A
=> Direct log output to stderr

internal/modules/modules.go, internal/modules/modules_test.go, main_test.go
We are doing a connectivity check that is unnecessary as things will fail just fine when invoking `go` without having connectivity if downloads are required.
Closes #70.
N.A
=> Remove unnecessary connectivity check

internal/printer/printer.go, internal/util/fileutil.go, main.go
Simplify the CLI by removing the `--force` flag.
N.A
=> Update direct dependencies

internal/analysis/analysis_test.go, internal/completion/gen/gen_test.go, internal/modules/modules_test.go, internal/testutil/test_module.go, main_test.go
Switch to use the new Go 1.15 features of `testing.T`.
Updated tests.
=> Use Go 1.15 t.TempDir()

internal/query/grammar.go, internal/query/parser.go, internal/query/parser_test.go, internal/query/tokenizer.go, internal/query/tokenizer_test.go, internal/query/tokens.go
A fully-fledged lexer and LALR parser for the new string-based query language for `gomod`.
Both the lexer and parser are fully and thoroughly unit-tested.
=> Query parser

internal/query/parser.go
Removal of superfluous repeat-shift logic. We should never be shifting more than once as repeated-shifts are triggered by rewinding the token stream.
Existing unit-tests.
=> Simplify query parser

internal/analysis/analysis.go, internal/depgraph/deps_mod.go, internal/depgraph/deps_pkg.go, internal/depgraph/filters/arbitrary_modules.go, internal/depgraph/filters/non_shared_modules.go, internal/depgraph/filters/target_modules.go, internal/depgraph/graph.go, internal/depgraph/module.go, internal/depgraph/package.go, internal/depgraph/parser.go, internal/depgraph/query.go, internal/graph/graph.go, internal/graph/graph_test.go, internal/reveal/replacements.go, internal/reveal/replacements_test.go, main.go
Wire support for the new query language into the `internal/depgraph` package.
None while the filtering API is being reworked. Tests will be added once the rewrite is done.
=> Add query filters

internal/depgraph/query.go, internal/util/exec.go
Add a "shared" query filter to replicate the behaviour of the `--shared` flag in `gomod graph`.
Not yet. Soon :tm:
=> Add shared filter

README.md, RELEASE_NOTES.md, internal/depgraph/deps_pkg.go, internal/depgraph/query.go, main.go, main_strings.go, mdl_style.rb
Expose the newly added querying language in the CLI of `gomod`.
Not yet. :disappointed:
=> Query parsing

internal/depgraph/query.go
Split-up and refactor the implementations of the filtering of the depgraph based on a given query. Also log warnings for (sub)queries returning empty results.
N.A
=> Refactor graph query implementations

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
=> Update GitHub templates

RELEASE_NOTES.md
=> Prepare 0.6.0 release

internal/depgraph/package.go, internal/depgraph/query.go
Another missing interface implementation.
Add a compile-time check that the type implements the interface.
=> Ensure depgraph.Package implements testAnnotated

docs/release-notes/next.md, docs/release-notes/v0.6.2.md
=> Prepare 0.6.2 release-notes

README.md
Added installation block in README.md
No tests for README.md
=> added installation block to README.md

internal/depgraph/deps_pkg.go, internal/modules/modules.go
=> Enforce module-mode in vendored projects
